version: '3.4'

services:
  master:
    image: skasip/eg3_master
    networks:
      - eg3_master
    ports:
      - 5000:5000
    environment:
      - DATABASE_HOST=master_db
    build: ./mc-service

  master_db:
    image: skasip/eg3_master_db
    volumes:
      - master_db-data:/data
    networks:
      - eg3_master
    ports:
      - 6379:6379
    build: ./mc-db

volumes:
  master_db-data:

networks:
  eg3_master:
